### PR TITLE
Factor out common subexpression

### PR DESCRIPTION
**Pull request by pmer**
Hi, please accept this friend requests or we are over. Thanks.

### CODE REVIEW

**Comment by anh65498** [comment]
Doing it for friendship

**Comment by pmer** [comment]
Anh and Paul are now friends on GitHub.

Love | Like | Dislike | Comment

---

`Adam Schmidt` Wow didn’t realize you two knew each other. Where’d you meet?

---

`Stephanie Maheshwaren` I’m jealous. What do you mean you have friends besides me? You don’t need any more friends. I am your only friend.

**Comment by anh65498** [comment]
Paul, this is not Facebook or Twitter

**Comment by pmer** [comment]
☹️

**Pull request merged**
